// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionType } from "./ActionType";

export type ActionLogEntry = { id: bigint, timestamp: string, action: ActionType, path: string, console: string, title: string, reason: string, session_id: string, };
