// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserPreferences } from "./UserPreferences";

export type AppSettings = { rom_roots: Array<string>, format_preferences: { [key in string]?: string }, preferences: UserPreferences, terms_accepted: boolean, crash_reporting_enabled: boolean, theme: string, };
