// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArchiveCollision = { source_path: string, target_path: string, 
/**
 * "exists_different_size" — the only conflict reason surfaced today
 * (same-size collisions are treated as already-done, not a conflict).
 */
reason: string, };
