// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompressCandidate } from "./CompressCandidate";
import type { DirSpace } from "./DirSpace";

export type CompressPreview = { candidates: Array<CompressCandidate>, total_source_bytes: number, available_space: Array<DirSpace>, };
