// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompressCandidate = { path: string, filename: string, console: string, 
/**
 * The source file's own parent directory, formatted identically to
 * `DirSpace.parent_dir` so the frontend can group candidates by directory
 * with an exact string match.
 */
parent_dir: string, source_size: number, 
/**
 * True when a matching .zip already exists with the same content size —
 * compressing would be a no-op; the source file is safe to delete directly.
 */
already_compressed: boolean, };
