// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConsoleStats = { name: string, 
/**
 * All ROM files regardless of category (games + hacks + BIOS + demos + …)
 */
total_files: number, 
/**
 * Unique title groups across all categories (canonical-level, deduplicated)
 */
total_groups: number, 
/**
 * ROM files that are FileCategory::Game only (matches ROMs-tab counts)
 */
game_files: number, 
/**
 * Unique game title groups (canonical-level, game category only)
 */
game_groups: number, preferred_count: number, 
/**
 * Subset of preferred_count where the ROM has an explicit language tag matching the preference.
 */
preferred_explicit_count: number, 
/**
 * Subset of preferred_count matched via region→language inference (no explicit tag).
 */
preferred_inferred_count: number, marked_for_deletion: number, bytes_to_free: number, total_bytes: number, };
