// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConsoleStats = { name: string, total_files: number, preferred_count: number, marked_for_deletion: number, bytes_to_free: bigint, };
