// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DatFile = { console: string, filename: string, version: string | null, entry_count: number, imported_at: string, };
