// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeletionReason } from "./DeletionReason";
import type { RomFile } from "./RomFile";

export type DeletionItem = { rom: RomFile, reason: DeletionReason, };
