// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsoleStats } from "./ConsoleStats";
import type { DeletionItem } from "./DeletionItem";
import type { RomFile } from "./RomFile";

export type DeletionPlan = { to_delete: Array<DeletionItem>, to_keep: Array<RomFile>, no_preferred_version_count: number, total_bytes_freed: number, console_summary: Array<ConsoleStats>, };
