// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeletionReason = "non_preferred_language" | "prerelease" | "older_revision" | "unofficial" | "format_pair_non_preferred" | "no_preferred_version";
