// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Free space available in one directory. Carries no "needed" figure — how
 * many bytes are actually needed depends on which candidates the user has
 * selected, which is a frontend-only, live-changing concern; the frontend
 * computes that itself from the checked candidates' sizes and compares it
 * against `available_bytes` here.
 */
export type DirSpace = { parent_dir: string, available_bytes: number, };
