// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a preferred variant chosen for the download list.
 *
 * Note: `BestAvailable` is intentionally absent. `build_group()` only sets
 */
export type DownloadStatus = "preferred" | "prerelease_only" | "fallback_only";
