// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadStatus } from "./DownloadStatus";
import type { FileCategory } from "./FileCategory";

/**
 * One entry in a download list — the preferred variant for a single title group.
 */
export type DownloadEntry = { 
/**
 * Exact ROM filename from the DAT `<rom name="…">` attribute
 * (e.g. `"Super Mario 3D Land (USA) (En,Fr,De,Es,Pt,It).3ds"`).
 */
rom_name: string, 
/**
 * Human-readable game title from the DAT `<game name="…">` attribute.
 */
game_title: string, title_normalized: string, regions: Array<string>, languages: Array<string>, status_flags: Array<string>, file_category: FileCategory, status: DownloadStatus, score: number, };
