// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a preferred variant chosen for the download list.
 *
 * Note: `BestAvailable` is intentionally absent. `build_group()` only sets
 * `preferred_idx` when `has_preferred = true`, which requires at least one
 * variant with `matches_preferred_language = true` — so the chosen variant
 * always has a language match. Titles with no language match (e.g. Japan-only
 * for an English user) surface via `DownloadList::excluded_count` instead.
 */
export type DownloadStatus = "preferred" | "prerelease_only";
