// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadEntry } from "./DownloadEntry";

/**
 * Full result of a `generate_download_list` command call.
 */
export type DownloadList = { console: string, to_download: Array<DownloadEntry>, 
/**
 * Count of DAT entries with a parseable `rom_name` (0 → re-import needed).
 */
total_in_dat: number, preferred_count: number, prerelease_only_count: number, 
/**
 * BIOS / amiibo entries included despite no language match (best-available variant).
 */
fallback_count: number, 
/**
 * Groups with no language-matching variant (regular ROM titles, not BIOS/amiibo).
 */
excluded_count: number, };
