// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnrichmentStatus = { running: boolean, enriched: number, total: number, current_title: string | null, };
