// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FailedFile } from "./FailedFile";

export type ExecutionResult = { success_count: number, failed: Array<FailedFile>, skipped_count: number, 
/**
 * Source directories that were empty after file deletion and were removed.
 * Also removed from rom_roots. Empty vec for regular execute_prune calls.
 */
folders_removed: Array<string>, };
