// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtractCandidate = { path: string, filename: string, console: string, 
/**
 * The zip's own parent directory, formatted identically to `DirSpace.parent_dir`
 * so the frontend can group candidates by directory with an exact string match.
 */
parent_dir: string, compressed_size: number, uncompressed_size: number, entry_count: number, 
/**
 * True when every entry already exists on disk with a matching size —
 * extracting would be a no-op; the zip is safe to delete directly.
 */
already_extracted: boolean, };
