// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArchiveCollision } from "./ArchiveCollision";
import type { FailedFile } from "./FailedFile";

export type ExtractionResult = { success_count: number, failed: Array<FailedFile>, collisions: Array<ArchiveCollision>, deleted_count: number, total: number, };
