// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirSpace } from "./DirSpace";
import type { ExtractCandidate } from "./ExtractCandidate";
import type { FailedFile } from "./FailedFile";

export type ExtractPreview = { candidates: Array<ExtractCandidate>, 
/**
 * Zip files that failed to open/parse — surfaced, not silently dropped.
 */
invalid: Array<FailedFile>, total_compressed_bytes: number, total_uncompressed_bytes: number, available_space: Array<DirSpace>, };
