// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilterSettings = { remove_unofficial: boolean, keep_unofficial_as_fallback: boolean, };
