// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilterSettings = { keep_preferred_only: boolean, remove_if_no_preferred_version: boolean, remove_prerelease: boolean, remove_unofficial: boolean, remove_older_revisions: boolean, keep_unofficial_as_fallback: boolean, };
