// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FormatPair = { console_group: string, 
/**
 * The smaller (subset) folder — every title here also appears in folder_b.
 */
folder_a: string, 
/**
 * The larger (superset) folder, or equal-sized when counts match.
 */
folder_b: string, overlap_percent: number, 
/**
 * Number of distinct normalized titles in folder_a (the subset).
 */
folder_a_count: number, 
/**
 * Number of distinct normalized titles in folder_b (the superset).
 */
folder_b_count: number, };
