// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameMetadata = { title_normalized: string, console: string, igdb_id: bigint | null, name: string | null, release_year: number | null, genres: Array<string>, summary: string | null, 
/**
 * IGDB community crowd score (0–100).
 */
rating: number | null, 
/**
 * IGDB aggregated critic/press score (0–100). Null when IGDB has no critic data.
 */
critic_rating: number | null, cover_url: string | null, };
