// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional filter applied to get_history queries.
 * action values are the snake_case DB strings: "moved_to_trash", "deleted", etc.
 */
export type HistoryFilter = { 
/**
 * Restrict to entries whose action is one of these values.
 */
actions: Array<string> | null, 
/**
 * Restrict to entries within the last N days.
 */
since_days: number | null, };
