// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned by get_interrupted_session when there are pending action_log rows.
 */
export type InterruptedSession = { pending_count: number, 
/**
 * Distinct console names from pending rows, alphabetically sorted.
 */
consoles: Array<string>, };
