// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OnboardingState = { terms_accepted: boolean, crash_reporting_opted_in: boolean, preferences_configured: boolean, roots_added: boolean, first_scan_complete: boolean, is_complete: boolean, };
