// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionLogEntry } from "./ActionLogEntry";

export type PagedHistory = { total: number, page: number, per_page: number, entries: Array<ActionLogEntry>, };
