// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayStatus } from "./PlayStatus";

export type PlayEntry = { id: string, title_normalized: string, console: string, status: PlayStatus, rating: number | null, notes: string | null, compat_notes: string | null, created_at: string, updated_at: string, synced_at: string | null, display_title: string | null, community_score: number | null, critic_score: number | null, };
