// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayStats = { backlog: number, testing: number, playing: number, completed: number, dropped: number, total_rated: number, avg_rating: number | null, };
