// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileCategory } from "./FileCategory";

export type QbtFileDecision = { filename: string, download: boolean, size_bytes: number, 
/**
 * Empty string for files that failed to parse — never matches a Starts-With chip.
 */
title_normalized: string, regions: Array<string>, languages: Array<string>, status_flags: Array<string>, file_category: FileCategory, };
