// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QbtFileDecision } from "./QbtFileDecision";
import type { QbtGroupInfo } from "./QbtGroupInfo";

export type QbtFilterPreview = { 
/**
 * Console name inferred from torrent folder, if detectable
 */
console_name: string | null, total: number, to_download: number, to_skip: number, 
/**
 * Every file in the torrent with its download/skip decision
 */
files: Array<QbtFileDecision>, 
/**
 * Only groups where >1 variant exists (single-variant groups are silently kept)
 */
multi_variant_groups: Array<QbtGroupInfo>, };
