// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QbtGroupInfo = { 
/**
 * Normalized lowercase group key — used as a stable React key, not for display
 */
key: string, 
/**
 * Properly-cased display title (pre-region portion of the chosen filename)
 */
display_title: string, 
/**
 * Chosen filename (will be set to priority 1)
 */
chosen: string, 
/**
 * Skipped filenames (will be set to priority 0)
 */
skipped: Array<string>, };
