// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileCategory } from "./FileCategory";

export type QbtGroupInfo = { 
/**
 * Normalized lowercase group key — used as a stable React key, not for display
 */
key: string, 
/**
 * Properly-cased display title (pre-region portion of the chosen filename)
 */
display_title: string, 
/**
 * Chosen filename (will be set to priority 1)
 */
chosen: string, 
/**
 * Skipped filenames (will be set to priority 0)
 */
skipped: Array<string>, 
/**
 * The preferred variant's title_normalized — for the Starts-With filter chip
 */
title_normalized: string, 
/**
 * The preferred variant's regions
 */
regions: Array<string>, 
/**
 * The preferred variant's languages
 */
languages: Array<string>, 
/**
 * The preferred variant's status_flags (e.g. "Beta", "Proto")
 */
status_flags: Array<string>, 
/**
 * The preferred variant's file category
 */
file_category: FileCategory, };
