// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QbtSettings = { host: string, user: string, has_password: boolean, no_auth: boolean, };
