// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QbtTorrent = { hash: string, name: string, num_files: number, 
/**
 * Immediate parent folder of the torrent files (e.g. "Nintendo - amiibo").
 * `None` when the torrent has no sub-folder structure.
 */
console_folder: string | null, };
