// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileCategory } from "./FileCategory";
import type { FileFormat } from "./FileFormat";

export type RomFile = { path: string, filename: string, console: string, title: string, title_normalized: string, regions: Array<string>, languages: Array<string>, status_flags: Array<string>, extra_tags: Array<string>, bad_dump: boolean, revision: number, disc_number: number | null, version: string | null, is_bios: boolean, file_format: FileFormat, file_category: FileCategory, filesize: number, 
/**
 * Computed from UserPreferences at grouping time — never hardcoded.
 */
matches_preferred_language: boolean, matches_preferred_region: boolean, };
