// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RomFile } from "./RomFile";

export type RomGroup = { title_normalized: string, console: string, variants: Array<RomFile>, 
/**
 * None when no variant matches the user's preferred language → delete all.
 */
preferred_idx: number | null, has_preferred_version: boolean, is_format_pair: boolean, 
/**
 * >1 means this group contains multi-disc files that are kept/deleted together.
 */
disc_count: number, 
/**
 * Original-case catalog number (e.g. "4B-001, Sachen-Commin") when this group
 * was split from others sharing the same title by a catalog-number extra_tag.
 * None for the vast majority of groups that have no catalog number.
 */
catalog_number: string | null, };
