// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPreferences = { 
/**
 * e.g. ["En"] or ["En", "Fr"] — ordered, first = most preferred
 */
preferred_languages: Array<string>, 
/**
 * Ordered priority list; user drag-reorders in Settings
 */
preferred_regions: Array<string>, 
/**
 * Show abbreviated console names (GBA, NES) instead of full names
 */
short_console_names: boolean, };
