// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FormatPair = { console_group: string, folder_a: string, folder_b: string, overlap_percent: number, };
