// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RomGroup } from "./RomGroup";

export type PagedGroups = { total_groups: number, page: number, per_page: number, groups: Array<RomGroup>, };
