// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RomFile } from "./RomFile";

export type RomGroup = { title_normalized: string, console: string, variants: Array<RomFile>, 
/**
 * None when no variant matches the user's preferred language → delete all.
 */
preferred_idx: number | null, has_preferred_version: boolean, is_format_pair: boolean, 
/**
 * >1 means this group contains multi-disc files that are kept/deleted together.
 */
disc_count: number, };
