// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScanStatus = { scanning: boolean, scanned: number, total_estimate: number, current_console: string | null, cached: boolean, };
